[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "countergen"
authors = [{name = "SaferAI", email = "saferai.audit@gmail.com"}]
dynamic = ["version", "description"]
